<Project>
  <!--Last updated package versions: February 10, 2026.-->

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Net10>10.0.3</Net10>
    <Net11>11.0.0-preview.1.26104.118</Net11>
  </PropertyGroup>

  <ItemGroup Label="For EF Core.">
    <!-- To use the .NET 11 preview packages, change the versions below from $(Net10) to $(Net11). -->
    <!-- Your projects should target net11.0 and you must install .NET 11 Preview SDK. -->

    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(Net10)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(Net10)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(Net10)" />
  </ItemGroup>

  <ItemGroup Label="For unit testing.">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup Label="For Blazor.">
    <PackageVersion
      Include="Microsoft.AspNetCore.Components.WebAssembly.Server"
      Version="$(Net10)"
    />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(Net10)" />
    <PackageVersion
      Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"
      Version="$(Net10)"
    />
  </ItemGroup>

  <ItemGroup Label="For web services.">
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="$(Net10)" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.12.36" />
  </ItemGroup>
</Project>
